### ISSUE TITLE
Migrating to TypeScript

### ISSUE THREAD

**Issue by sr229** [LeNitrous/Nimi#8]
Currently `master` is very "hacky" in its current state, and won't be able to scale or properly move hosts. I discussed with @LeNitrous on possibly allowing this to run on serverless platforms but in order to do that, we need to rewrite the entire codebase from the ground up:

## Todo List

- [x] Use [Next.js](https://nextjs.org) as basis for the API
- [x] Finish porting over mixins, models, and remotes.
- [x] Write new middleware (as most middleware code wrote for the previous codebase is not applicable for Next.js).

This would allow maintenance of the API to be much more easier and predictable as we would have less worries writing code that may have unpredictable behavior - and this would allow much more cleaner code in the future as well as TypeScript enforces strict typing discipline: something we would want as Nitrous and I come from C-based languages.

**Comment by sr229** [comment]
As of 9/25, the only thing missing is the models and the mixins, the rest of the backend is already mature.

**Comment by tommywalkie** [comment]
As discussed with @LeNitrous, I'm working on some TypeScript-compatible unit testing feature in [`setup-tests`](https://github.com/LeNitrous/azur-lane-api/tree/setup-tests) branch, using [`uvu`](https://github.com/lukeed/uvu) test runner. A `test` npm script will be available.

- [x] Implement `uvu`
- [x] Try fetching a ship, from an unit test ([example](https://github.com/LeNitrous/azur-lane-api/blob/7904be597e6223ee18b548e61705be8e5e779f19/tests/index.ts#L19-L22))
- [ ] Use a Github Actions workflow to run the script

**Comment by sr229** [comment]
API is now complete, this is now merging back to master.

**Comment by sr229** [comment]
Checklist is now completed. Tasks here are all done.
